[package]
name = "ezrstudio"
version = "0.1.0"
authors = ["Hui-Hong You <hiroshi@ghostsinthelab.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
