apiVersion: apps/v1
kind: Deployment
metadata:
  name: easy-rstudio-user-default-deployment
spec:
  selector:
    matchLabels:
      app: easy-rstudio
  replicas: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: easy-rstudio
        user: default
    spec:
      containers:
      - name: easy-rstudio-container
        image: rocker/rstudio
        env:
        - name: ROOT
          value: "true"
        - name: PASSWORD
          value: "easy-rstudio"
        ports:
        - containerPort: 8787