apiVersion: v1
kind: Pod
metadata:
  name: easy-rstudio-pod
  namespace: easy-rstudio
  labels:
    app: easy-rstudio
spec:
  containers:
  - name: easy-rstudio-container
    image: rocker/rstudio
    env:
    - name: ROOT
      value: "true"
    - name: PASSWORD
      value: "easy-rstudio"
    ports:
    - containerPort: 8787